#!/usr/bin/python3
# -*- coding: utf-8 -*-

# Copyright © 2014 Martin Ueding <dev@martin-ueding.de>

import argparse
import subprocess
import os
import tempfile

def main():
    options = _parse_args()

    with tempfile.TemporaryDirectory() as tempdir:
        subprocess.check_call([
            'pdftk', options.xournalfile, 'burst', 'output',
            os.path.join(tempdir, '%04d.pdf'),
        ])
        page_files = [os.path.join(tempdir, x) for x in sorted(os.listdir(tempdir)) if x.endswith('.pdf')]
        print(page_files)


def _parse_args():
    """
    Parses the command line arguments.

    :return: Namespace with arguments.
    :rtype: Namespace
    """
    parser = argparse.ArgumentParser(description="")
    parser.add_argument('xournalfile')
    options = parser.parse_args()

    return options

if __name__ == "__main__":
    main()
